version: "3"

services:   
  db:
    image: mariadb  

  dj:
    container_name: dj
    build: backend
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./backend:/code
    ports:
      - "80:80"
    depends_on:
      - db
  
  ng:
    container_name: ng
    build: frontend
    ports:
      - "4200:80"